### ISSUE TITLE
Mouse clicks after suspend are wrong

### ISSUE THREAD

**Issue by hahuang65** [r-c-f/waynergy#10]
I'm not sure if this is a waynergy bug because if the bug happens, and I switch my mouse to a direct connection instead of waynergy, the error is still manifested, BUT I haven't been able to reproduce without waynergy. That said, I haven't found out how to reproduce it reliably, but am reporting it just to see if you might have any thoughts.

Twice, when I wake my Arch laptop up from suspension, mouse clicks in certain sections of certain programs do strange things.
I use `sway` as my window manager.

When I click on a text field in Firefox, or Ferdi, it works just fine. Slack also works fine.
If I click on a video in Firefox, it will play/pause.

Anywhere else in Firefox, like swtiching tabs, doesn't work. Sometimes, like right now as I'm writing this, the functionality comes back and clicking on tabs works.

`kitty` doesn't respond at all. And when I click in a `kitty` window, or any other program where the mouse click doesn't register in the program, it does a weird thing:

I have 4 workspaces defined in sway. I don't have a fifth one defined. But when a click doesn't register in a program, it seems to open a 5th workspace (I can see it in my waybar, that it becomes the active workspace), but what's in my monitor view is still the workspace I was on. I'm guessing that my clicks are going to this 5th, hidden workspace.

**Comment by hahuang65** [comment]
I think this is a sway issue actually. Going to close here.

**Comment by r-c-f** [comment]
Should it turn out not to be a sway bug, the ideal information would be a debug log. If it can't be readily reproduced and you just leave it running, be sure to prune it to the relevant time span only given that debug logs contain keystrokes and you'd probably not want that in a public place.
