### ISSUE TITLE
[Bug] 100% CPU utilization after random time

### ISSUE THREAD

**Issue by PJungkamp** [r-c-f/waynergy#12]
Thank you for your amazing work on waynergy! It mostly works great (way better than barrier under windows did for me)!
 
But after a random amount of time (some times 30min, other times multiple hours) waynergy becomes irresponsive and drains my battery by fully utilizing a single core.

I'd appreciate a hint to where I need to look.

I sadly can't tell how to reproduce this. I already tried forcing it by switching the network or randomly restarting/suspending the server. But that does not seem to do it.

I am running sway on Arch Linux with a Barrier server and encryption.

**Comment by r-c-f** [comment]
Thank you for the report; there are definitely ways to debug this even without a straightforward reproduction. The ideal would probably be to build with debugging symbols and attach gdb to get a backtrace, though barring that a log would potentially be useful to get a general idea of what's triggering the spinning behavior.

**Comment by PJungkamp** [comment]
Sorry for taking so long. I logged some actions and it seems like there's a problem when there is temporarily no network device available.

When I change my WiFi network the Debug output explodes: [waynergy-no-hostnames.log](https://github.com/r-c-f/waynergy/files/6650246/waynergy-no-hostnames.log)

**Comment by PJungkamp** [comment]
I suspect it's the main loop in main.c:279 which spins on the syn_connect function:
```
1. main():                     m_connected == false -> uSynergyUpdate
2. uSynergyUpdate():  m_connected == false and no errors fatal -> m_connectFunc=syn_connect
3. syn_connect():         
        getaddrinfo() returns a null pointer as res since there is no network adapter
        -> return false 
        -> back to main loop
```

Does this sound about right?
Haven't tried fixing it yet since I'm currently back on Windows.

Should there be a delay or should waynergy abort when there are no addresses available?

**Comment by r-c-f** [comment]
#13 should make this situation more manageable by adding in the standard delay for other failure modes. If not, an incremental back-off approach can be added instead.

**Comment by PJungkamp** [comment]
That seems to have fixed the CPU utilization (no more 100% on disconnect). Thank you!

**Comment by r-c-f** [comment]
No problem, thank you for the report

**Comment by PJungkamp** [comment]
There's still a detail missing! I just recognized that the outer main loop is missing a sigHandleRun!

If idling in disconnected state no signals are handled!.
Should be just an addition of sigHandleRun() after uSynergyUpdate() in main loop.

**Comment by r-c-f** [comment]
That would indeed be an issue; pushed a new commit which does this. So hopefully it can be killed without the need for -9.
