### ISSUE TITLE
Error: Compositor does not support wlr_virtual_pointer_unstable_v1 (Ubuntu 21.10 with KDE)

### ISSUE THREAD

**Issue by sj** [r-c-f/waynergy#18]
I built Waynergy on Ubuntu 21.10 (using `libtls` and `libtls-dev` from Ubuntu Jammy). Compilation all good. But when I try to run it, I get:

```
$ waynergy --host 192.168.0.127
Child died:
72814
Status:
127
0.000000287: [WARN] wl-clipboard not found, no clipboard synchronization support
0.011572502: [ERROR] Compositor does not support wlr_virtual_pointer_unstable_v1
```

I'm not worried about the clipboard warning — it's the `[ERROR]` that I'm worried about. I'm running Wayland 1.19 with KDE 5.22 (both from Ubuntu Impish).

Am I doing something wrong? Would really appreciate your advice. Thanks!

**Comment by r-c-f** [comment]
Unfortunately this is an issue on the KDE end of things -- virtual input is nonstandard in Wayland, and only sway et al. are going to work here. I suspect they're going to follow GNOME and back the libei approach eventually, in which case barrier/synergy proper will be the eventual solution.

**Comment by r-c-f** [comment]
Actually disregard that previous comment, it looks like plasma does have its own fake input protocol and it doesn't look like it'd be too much work to support it.

**Comment by r-c-f** [comment]
On further inspection the protocol for fake keyboard input appears to be a bit more limited than the one used for wlroots, so a quick and dirty patch for KDE won't be quite so quick.

**Comment by r-c-f** [comment]
@sj with #20 it should mostly work. There are some caveats regarding keyboard handling but it's good enough to let me type this message in a Plasma desktop.
