### ISSUE TITLE
Reconnection does not work

### ISSUE THREAD

**Issue by ccoenen** [r-c-f/waynergy#25]
When I lose the connection to a server, reconnection attempts all fail. For example: if I put my client (with waynergy) into standby, the connection is obviously lost. But after waking the machine up again, I only get

```
[INFO] Going to connect to ... at port 24800
[ERROR] Connection attempt failed, trying to reconnect in a second
(... rinse, repeat ...)
```

If I kill the process and restart it, it connects instantly.

**Comment by r-c-f** [comment]
The log should now be more useful in master, the output of which would be much appreciated. 

As for the annoyance in the meantime it can be slightly alleviated by using `SIGUSR1` when killing, which triggers a re-execution with just one command.

**Comment by ccoenen** [comment]
I'm currently not getting that same error any more. I've been running the new `main` branch including #c027e86 for ~4 hours now. I'll keep it on loglevel 4 and log to a file. If it ever comes up again I'll report back!

**Comment by ccoenen** [comment]
I can't _yet_ tell you why it happens or when exactly, but now I got the error again:
```
37604.142046551: [INFO] Going to connect to (hostname redacted) at port 24800
37604.142354866: [ERROR] getaddrinfo failed: System error
37604.142440250: [ERROR] Connection attempt failed, trying to reconnect in a second
```

I may have found somethin interesting though: Before it turns to the pattern above, I get a different error message a bunch of times:
```
28340.477579946: [INFO] Going to connect to (hostname redacted) at port 24800
28343.540930744: [ERROR] syn_connect_setup: connect: No route to host
28346.612888544: [ERROR] syn_connect_setup: connect: No route to host
28349.685005227: [ERROR] syn_connect_setup: connect: No route to host
28349.685132832: [ERROR] Connection attempt failed, trying to reconnect in a second
```

and the **FINAL** one before the ever-repeating pattern does _this_:
```
28422.141592954: [INFO] Going to connect to (hostname redacted) at port 24800
28425.204927134: [ERROR] syn_connect_setup: connect: No route to host
28428.276934869: [ERROR] syn_connect_setup: connect: No route to host
28428.277118692: [ERROR] syn_connect_setup: socket: Too many open files    <----------------------
28428.277175311: [ERROR] Connection attempt failed, trying to reconnect in a second
```

So I could imagine socket handles not being fully closed or discarded or something, and piling up until the process can't open any new ones? Or something like that?

I still have the log file If you would like to know more or if I should analyse timings or count the messages or something like that.

**Comment by r-c-f** [comment]
That does seem to be the case. Now that a full and proper cleanup on a connect error is consolidated into one place (after each failed attempt while iterating though the results of `getaddrinfo()`) it should hopefully stop leaking file descriptors.

**Comment by ccoenen** [comment]
I am now running `b113ebe`, since this always takes a few hours to reproduce, I would suggest we consider this "fixed" unless it comes up again. I promise to report back if anything like this happens again.

Thank you for your work and support! I really appreaciate it!

**Comment by ccoenen** [comment]
(for future reference: I looked up how long that took; the disconnection took place at 23224 seconds in, the too many files error was at 28428 seconds; so it took about 5204 seconds OR (86 minutes) to develop this kind of behaviour. This resulted in a count of 509 attempted reconnects, which is awfully close to 512 :-D
(My open files limit for regular processes is 1024)

**Comment by ccoenen** [comment]
I can confirm that I'm able to reconnect succesfully after over 2 hours of the server in standby.
