### ISSUE TITLE
Windows Host / Sway Client: Keyboard prints wrong characters

### ISSUE THREAD

**Issue by dankles** [r-c-f/waynergy#3]
## What works 
- Mouse works fine. Left click, right click and mouse wheel all tested fine.
- copy/paste works as well, both from host to client and client to host.

## What doesn't work
The keymap translation between my Windows host and Sway client seems to be messed up. `a` becomes `u`, `s` becomes `i`, etc. 

On the linux/sway side, I ran `setxkbmap -print > ~/.config/waynergy/xkb_keymap`, which gives:
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

I use a standard 105 key US keyboard. Nothing fancy. Is there anything on windows that I would need to change? Is windows even supported here?

EDIT: 
On the host I'm running barrier 2.3.3

**Comment by r-c-f** [comment]
For UNIXy platforms it's been easier to pass the raw scancodes and let xkb use the pre-existing mappings; this is probably a good reason to see if xkb will tolerate an `xkb_keycodes` section using the platform-agnostic Synergy key IDs at some point in the next few days.

**Comment by r-c-f** [comment]
...and indeed writing an xkb mapping to accept arbitrary UTF32 is probably not going to happen. However, using 
[this keycodes section](https://github.com/r-c-f/waynergy/files/6243193/win.txt) does work for me -- with that in `~/.xkb/keycodes/win` and 
```
xkb_keymap {
	xkb_keycodes  { include "win+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```
as the keymap configuration I was able to get it to work with a Windows primary. Some keys are missing (I don't actually own a working full-sized keyboard it would seem) but the relevant keycodes can be found in `wev` or `xev` or the like.

**Comment by dankles** [comment]
That seems to work. Thanks for the assist!

**Comment by videogame-hacker** [comment]
This works, but it still emits the wrong characters if you're typing into an XWayland window for some reason :(

**Comment by r-c-f** [comment]
I've updated the example windows key map to use an offset of 7, which should placate X.
