### ISSUE TITLE
current main broke raw-keymap.offset

### ISSUE THREAD

**Issue by ccoenen** [r-c-f/waynergy#30]
somehow https://github.com/r-c-f/waynergy/commit/74125ece3dd7b8937304ef39ea09b002a1085f28 broke the raw keymap.offset, so my keymap I created in #27 is no longer working as expected. I'm investigating now.

**Comment by ccoenen** [comment]
somehow, despite the startup saying `using INI value for raw-keymap/offset: 8` on startup, that is no longer being applied.

when I press "a" on the server, the client types a "u" (or keycode 30), as opposed to the previous behaviour where it wouldhave received 38 (basically the check from https://github.com/r-c-f/waynergy/issues/27#issuecomment-1022668553 but this time it turns out differently)

**Comment by ccoenen** [comment]
wait, I do have to double-check something.

**Comment by ccoenen** [comment]
One tiny thing that's buried in there, too:

https://github.com/r-c-f/waynergy/commit/74125ece3dd7b8937304ef39ea09b002a1085f28#diff-6282fc15995e77918033a56e50f652d44f40e8a01ac3a1fd68ade5280de89d23R115

This currently only lists `xkb_key_offset`, not `raw-keymap/offset` or `offset` (local variable). I am not sure if this is intended behaviour, but I just wanted to bring that up because the loglines with "offset 0" were slightly confusing to me.

**Comment by r-c-f** [comment]
This is now fixed in master.

**Comment by ccoenen** [comment]
can confirm :) it works fine now!

**Comment by r-c-f** [comment]
That was the intention, but because the offset is supposed to make things more convenient I've added an option to disable its application to explicit raw mappings.

**Comment by ccoenen** [comment]
thanks, this works fine as far as I can tell :-)
