### ISSUE TITLE
Waynergy does not recognize uinput 

### ISSUE THREAD

**Issue by brmnjsh** [r-c-f/waynergy#31]
### Issue:
Despite configuring uinput on my system, waynergy fails to start unless using root

### System:
Client: Fedora 35, with wayland
Server: Barrier on Windows 11

### Technical Context:
When starting up waynergy with `waynergy -c -e -t [ip address]` I receive:

```
uinput fd open failed (this is normal if not using uinput backend): Permission denied
...
Child died:
11446
Status:
1
0.000000169: [WARN] Could not kill lingering wlpaste instances: -1

Watch mode requires a compositor that supports wlroots data-control protocol
0.004254760Watch mode requires a compositor that supports wlroots data-control protocol
: [ERROR] Virtual input not supported by compositor
Child died:
11448
Status:
1

```

However when I run as root (`sudo -E waynergy -e -t -c 192.168.68.50`), waynergy does indeed start with the output:

```
Running as root, dropping ancilary groups
...
Child died:
11698
Status:
1
0.000000151: [WARN] Could not kill lingering wlpaste instances: -1

Watch mode requires a compositor that supports wlroots data-control protocol
Child died:Watch mode requires a compositor that supports wlroots data-control protocol

11699
Status:
1
Child died:
11700
Status:
1
0.009592139: [WARN] uinput does not support xkb keymaps -- use raw-keymap instead
0.009742334: [WARN] Idle inhibit request, but no idle manager support
```
So still quite a few `WARN`s and such popping up, that I don't quite know how to resolve at this point

My current uinput permissions/group/owner are:
`crw-rw----.  1 root   uinput     10,   223 Feb  6 18:32 uinput`

As instructed in the readme I created the group `uinput` and a rules file for input titled "49-input.rules (`-rw-r--r--. 1 root root    46 Feb  5 23:09 49-input.rules`) with the content of:
`KERNEL=="uinput",GROUP:="uinput",MODE:="0660"`

I then setgit as for /usr/local/bin/waynergy using:
```
chown :uinput waynergy`
chmod g+s waynergy
```
with the result:
`-rwxr-xr-x. 1 root uinput   279784 Feb  5 22:37 waynergy`

**Comment by brmnjsh** [comment]
looks like I failed to run `sudo chmod g+s waynergy` at some point...oops

**Comment by r-c-f** [comment]
The oops may well be on my part, there seems to be a typo in the `chown` bit with an extra backtick that wouldn't help if run exactly as shown
