### ISSUE TITLE
Clipboard content changes to Chinese characters

### ISSUE THREAD

**Issue by stintel** [r-c-f/waynergy#36]
Running barrier 2.4.0 server on Gentoo KDE Plasma and Waynergy 855ea2a867db758b40dcba64a1f8ba102ae830c5 on Fedora 36 KDE Plasma, clipboard content copied on Gentoo changes to Chinese characters once I move the cursor from Gentoo to Fedora.

![image](https://user-images.githubusercontent.com/1258811/169516945-2addfc59-39a0-4596-890b-8a7665b001bc.png)
![image](https://user-images.githubusercontent.com/1258811/169517324-c0b35578-414e-4fab-87f8-c485035e9e76.png)

It does not happen when I copy text from Kate, so I initially suspected it's font related. However, the font I'm using in Konsole on Gentoo is Droid Sans Mono, which is also installed on the Fedora machine. Simply moving the cursor from the Gentoo host to the Fedora host and moving it back, is enough to alter the clipboard content.

The problem does not seem to occur when I'm copying text on the Fedora machine and paste it on the Gentoo machine.

This problem does not occur between the same Barrier server and a Barrier client on macOS, so I suspect this is a Waynergy issue.

Would appreciate any suggestions as right now I always have to copy text in app X, paste in Kate, copy again in Kate, then paste on the Fedora machine. Easy to forget and extremely frustrating when you do.

**Comment by r-c-f** [comment]
I apologize for the delay...

This seems to be a weird one that I can't quite reproduce at first pass but I'll have a go with Plasma and Konsole in the near future. In the meantime, is there any way you could past the proper text and then the garbled text here? I'd want to see if there is some trivial misinterpration, or something much more broken going on.

**Comment by stintel** [comment]
> I apologize for the delay...

No worries, life happens to all of us ;-)


> This seems to be a weird one that I can't quite reproduce at first pass but I'll have a go with Plasma and Konsole in the near future. In the meantime, is there any way you could past the proper text and then the garbled text here? I'd want to see if there is some trivial misinterpration, or something much more broken going on.

Copying `foo` or `bar` in Konsole on the Gentoo barrier server and pasting it on the Fedora running Waynergy client results in `猼慰⁮瑳汹㵥昢湯⵴慦業祬洺湯獯慰散㸢猼慰⁮瑳汹㵥挢汯牯⌺〰〰〰戻捡杫潲湵ⵤ潣潬㩲昣晦晦㭦㸢潦㱯猯慰㹮戼㹲⼼灳湡`.

I accidentally Googled that recently, and found https://github.com/debauchee/barrier/issues/406 - it seems to be related to UTF-8.

**Comment by r-c-f** [comment]
That's actually extremely useful; it seems to mostly resemble an imprudent attempt at reading UTF-8 as if it were UTF-16 when playing with iconv. Not sure how lossless that is going to be round trip but I've at least got some ideas to play with, so thank you.

**Comment by r-c-f** [comment]
The solution seems to be to ignore anything but plain text to bypass the weird HTML conversion bugs as seen in the barrier issue. Does #39 fix it for you?

**Comment by stintel** [comment]
> Does #39 fix it for you?

Unfortunately not.

**Comment by stintel** [comment]
> Does #39 fix it for you?

It does. Few nits on the PR though.
