### ISSUE TITLE
Screen locker never starts when waynergy is connected

### ISSUE THREAD

**Issue by ackstorm23** [r-c-f/waynergy#49]
I have noticed that the screen locker *never* kicks on if my waynergy client is connected to my windows server.

1. This is true regardless of the state of the screen in windows.
2. If I disconnect waynergy from the windows host, the screen locker kicks in as it normally should.

How do I debug this to determine what is causing a constant state of activity on Linux?

config.ini

```
xkb_key_offset = 8

#[wlr]
#wheel_multi = 1

[raw-keymap]
offset = 0
offset_on_explicit = false
331 = 113  #LEFT
328 = 111  #UP
333 = 114  #RIGHT
336 = 116  #DOWN
338 = 118  #INS
327 = 110  #HOME
329 = 112  #PGUP
339 = 119  #DEL
335 = 115  #END
337 = 117  #PGDN
347 = 133  #WIN
312 = 108  #RALT
349 = 135  #MENU

284 = 104  #KPEN
325 = 77   #NMLK
309 = 106  #KP/

[screensaver]
start = pkill -SIGUSR1 swayidle
stop = pkill swaylock

[idle-inhibit]
method = mouse
interval = 30
keyname = HYPR

[log]
level = 6
mode = a
path = /tmp/waynergy.log

```

How I have configured swayidle

```
exec swayidle -w timeout 300 'gtklock' timeout 600 'swaymsg "output * dpms off"' \ 
resume 'swaymsg "output * dpms on"' before-sleep 'gtklock'
```

**waynergy version v0.0.12-2-gfb70628**

**Comment by ackstorm23** [comment]
I did not configure any of the idle-inhibit methods, so I will try it out in mouse mode and see if it works.

**Comment by r-c-f** [comment]
Can you post a short debug log from waynergy (preferably latest master) where the issue clearly occurs?

**Comment by ackstorm23** [comment]
I locked the screen in windows and walked away for about 20 minutes.   This is a shortened excerpt of a repeating pattern. 

> 4569.249497449: [DEBUG] Got CALV
> 4574.260542602: [DEBUG] Got CALV
> 4579.268031766: [DEBUG] Got CALV
> 4584.268185949: [DEBUG] Got CALV
> 4589.282641803: [DEBUG] Got CALV
> 4594.284546780: [DEBUG] Got CALV
> 4598.722353181: [DEBUG] Got idle event, responding with zero mouse move
> 4598.722562394: [DEBUG] Got resume event
> 4599.289602383: [DEBUG] Got CALV
> 4604.294070999: [DEBUG] Got CALV
> 4609.308122598: [DEBUG] Got CALV
> 4614.309468892: [DEBUG] Got CALV
> 4619.312591462: [DEBUG] Got CALV
> 4624.322099367: [DEBUG] Got CALV
> 4628.722697861: [DEBUG] Got idle event, responding with zero mouse move
> 4628.722802762: [DEBUG] Got resume event
> 4629.336347796: [DEBUG] Got CALV
> 4634.349328664: [DEBUG] Got CALV
> 4639.354601846: [DEBUG] Got CALV
> 4644.364786387: [DEBUG] Got CALV
> 4649.366033256: [DEBUG] Got CALV
> 4654.366104695: [DEBUG] Got CALV
> 4658.723021069: [DEBUG] Got idle event, responding with zero mouse move
> 4658.723179125: [DEBUG] Got resume event
> 4659.379815365: [DEBUG] Got CALV
> 4664.392444022: [DEBUG] Got CALV
> 4669.392175481: [DEBUG] Got CALV
> 4674.398948632: [DEBUG] Got CALV
> 4679.400134846: [DEBUG] Got CALV
> 4684.402517856: [DEBUG] Got CALV
> 4688.723361131: [DEBUG] Got idle event, responding with zero mouse move
> 4688.723511939: [DEBUG] Got resume event
> 4689.403359409: [DEBUG] Got CALV
> 4694.411149945: [DEBUG] Got CALV
> 4699.413069670: [DEBUG] Got CALV
> 4704.421220379: [DEBUG] Got CALV
> 4709.421293614: [DEBUG] Got CALV
> 4714.431726766: [DEBUG] Got CALV
> 4718.723661240: [DEBUG] Got idle event, responding with zero mouse move
> 4718.723864437: [DEBUG] Got resume event
> 4719.437450074: [DEBUG] Got CALV
> 4724.449047353: [DEBUG] Got CALV
> 4729.459056354: [DEBUG] Got CALV
> 4734.468031762: [DEBUG] Got CALV
> 4739.477641434: [DEBUG] Got CALV
> 4744.487127981: [DEBUG] Got CALV
> 4748.724026550: [DEBUG] Got idle event, responding with zero mouse move
> 4748.724098861: [DEBUG] Got resume event
> 4749.504401830: [DEBUG] Got CALV
> 4754.514789788: [DEBUG] Got CALV
> 4759.524114847: [DEBUG] Got CALV
> 4764.525445601: [DEBUG] Got CALV
> 4769.534800395: [DEBUG] Got CALV
> 4774.544374177: [DEBUG] Got CALV
> 4778.724292116: [DEBUG] Got idle event, responding with zero mouse move
> 4778.724478851: [DEBUG] Got resume event
> 4779.559052473: [DEBUG] Got CALV
> 4784.565469133: [DEBUG] Got CALV
> 4789.566718185: [DEBUG] Got CALV
> 4794.568762021: [DEBUG] Got CALV
> 4799.577432289: [DEBUG] Got CALV
> 4804.580413330: [DEBUG] Got CALV
> 4808.724587204: [DEBUG] Got idle event, responding with zero mouse move
> 4808.724726279: [DEBUG] Got resume event
> 4809.593925370: [DEBUG] Got CALV
> 4814.593907647: [DEBUG] Got CALV
> 4819.602587460: [DEBUG] Got CALV
> 4824.611811701: [DEBUG] Got CALV
> 4829.613093812: [DEBUG] Got CALV
> 4834.627394200: [DEBUG] Got CALV
> 4838.724799125: [DEBUG] Got idle event, responding with zero mouse move
> 4838.724909956: [DEBUG] Got resume event
> 4839.639218868: [DEBUG] Got CALV
> 4844.641852323: [DEBUG] Got CALV
> 4849.647703558: [DEBUG] Got CALV
> 4854.650095074: [DEBUG] Got CALV
> 4859.650360835: [DEBUG] Got CALV
> 4864.654794051: [DEBUG] Got CALV
> 4868.725045550: [DEBUG] Got idle event, responding with zero mouse move
> 4868.725184371: [DEBUG] Got resume event
> 4869.669101656: [DEBUG] Got CALV
> 4874.680079286: [DEBUG] Got CALV
> 4879.681469700: [DEBUG] Got CALV
> 4884.686000683: [DEBUG] Got CALV
> 4889.689310186: [DEBUG] Got CALV
> 4894.703097002: [DEBUG] Got CALV
> 4898.725385840: [DEBUG] Got idle event, responding with zero mouse move
> 4898.725561456: [DEBUG] Got resume event
> 4899.712593655: [DEBUG] Got CALV
> 4904.722510688: [DEBUG] Got CALV
> 4909.731764566: [DEBUG] Got CALV
> 4914.740079716: [DEBUG] Got CALV
> 4919.750517762: [DEBUG] Got CALV
> 4924.756729040: [DEBUG] Got CALV

The screen on Linux never turned off or or locked during this period.

**Comment by r-c-f** [comment]
It's looking like the server side isn't sending the appropriate screensaver enable message. Is screensaver synchronization enabled?

**Comment by ackstorm23** [comment]
> It's looking like the server side isn't sending the appropriate screensaver enable message. Is screensaver synchronization enabled?

After digging, it appears they removed it from 1.14.x all together.   If I attempt to use `screenSaverSync = true` in options it bails out with an invalid config,  other users on their forums claim it no longer works, and it's not listed in the UI at all anymore. 

Can I disable this on the waynergy end so that it no longer expects it?

**Comment by r-c-f** [comment]
#50 does add an `idle-inhibit/enable` setting, which when set to false should allow for this.

**Comment by ackstorm23** [comment]
> #50 does add an `idle-inhibit/enable` setting, which when set to false should allow for this.

TY!
