### ISSUE TITLE
Idle inhibit not working on GNOME

### ISSUE THREAD

**Issue by symposion** [r-c-f/waynergy#52]
I don't know if this is expected, but when running on Arch GNOME, waynergy does not inhibit idle. The logs say:

```
0.018020828: [DEBUG] got idle inhibit request
0.018024156: [WARN] Idle inhibit request, but no idle manager support   
```

Is that expected? If so, would i be possible to add it to the README? If not, is there some optional dependency that's required to make this work?

**Comment by r-c-f** [comment]
I wasn't aware they'd not implemented that protocol, but indeed it seems to be the case. I'll see if a workaround using `gnome-sesion-inhibit` is viable, as if it is, it wouldn't be much work.

**Comment by r-c-f** [comment]
Does #53 work on your end? It seems to do the job here.

**Comment by symposion** [comment]
Looks like that works! Thanks very much!
