### ISSUE TITLE
Waynergy client on kde wayland system.

### ISSUE THREAD

**Issue by popcorn9499** [r-c-f/waynergy#69]
Hello. I am running input-leap on my windows host and waynergy on a laptop.

Input-leap is version 2.4.0-release 282523a3
Waynergy is version 0.0.15

My issue is specifically I can get regular character keys to map. things like letters numbers etc, however all modifier keys and combinations of keys do not seem to register. I did run waynergy-mapper to correct the keymap and stored the raw-keymap it generated under .config/waynergy/config.ini which seemed correct. However I am not 100% positive.

I generated the waynergy-mapper keymap by running waynergy then pressing the keys it asked me. 

even after that and restarting waynergy I did not seem to be able to get the super/windows key to work or ctrl, alt etc. however shift did work which was nice. 

The command im running to launch waynergy is 
```
waynergy -b kde -d 192.168.1.18
```

Unsure if this is some sort of kde wayland limitation or waynergy not quite handling stuff correctly. 
Help would be greatly appreciated. Thank you!

**Comment by r-c-f** [comment]
Can you post the raw-keymap section you're using? Also, as a sanity check, if you run waynergy-mapper again (to try and correct the mapping again) does it generate any output?

**Comment by popcorn9499** [comment]
Sorry to waste your time. I apparently needed to remap another time. I guess I didn't press the right keys sometimes yesterday. Thank you for your time and have a great day
