### ISSUE TITLE
Mouse scrolling wheel

### ISSUE THREAD

**Issue by Bykow** [r-c-f/waynergy#70]
Context:
Server: MacOSx
Client: Archlinux w/ sway

Already done: 
All the config with xkb and keymaps. It works, it feels like a miracle came true for me !

Last standing issue:
Mouse wheel, when I scroll just once, on sway, it scrolls like a million kilometers at a time. I saw the paragraph at the end of the README but I'm not sure how to make this config..

**Comment by r-c-f** [comment]
This is fixed in the most recent commit, but for the release 
```
[wlr]
wheel_mult = 1
```
will fix it

**Comment by Bykow** [comment]
Thanks !
