### ISSUE TITLE
SSL error: Mac Barrier host, KDE Waynergy client, "unexpected EOF while reading"

### ISSUE THREAD

**Issue by moghingold** [r-c-f/waynergy#72]
I generated `~/.config/waynergy/tls/cert` with the following command:

`openssl req -x509 -nodes -days 3650 -subj /CN=Barrier -newkey rsa:4096 -keyout ./cert -out ./cert`

When I start Barrier on the Mac, I see the following output:

```
DEBUG: Opening new socket: 03CFDD20  
INFO: OpenSSL 3.0.0 7 sep 2021  
ERROR: ssl error occurred (generic failure)  
ERROR: error:0A000126:SSL routines::unexpected eof while reading  
ERROR: failed to accept secure socket  
INFO: client connection may not be secure
```

Obviously I can sort of work around this by disabling SSL but I would rather not do that. Is this an issue with Barrier for Mac OS, or an issue with how I generated and stored the client cert?

**Comment by r-c-f** [comment]
This should work in master now; I was not setting the private key properly for the client certificate.

**Comment by moghingold** [comment]
Confirmed fixed.
