### ISSUE TITLE
Cannot interact with input-leap

### ISSUE THREAD

**Issue by IDDQD69** [r-c-f/waynergy#77]
Hi,

I am running input-leap 2.4.0 on my server (wayland / kde)

and waynergy 0.0.16 on my host (wayland / kde)

Host can connect to the server alright but when I try to move my mouse to the host nothing happens. 

I get no log messages etc.

running waynergy with kde backend from the cli.

thanks for the help.

**Comment by IDDQD69** [comment]
Is it so, that inpu-leap doesn't work as as server when using wayland? Everything woks fine with X11.

**Comment by r-c-f** [comment]
input-leap have been hard at work on the problem, but for now it won't work. Once libei and portal support exists in Plasma, you'll be able use input-leap as a client and server and this project will be obsolete.
