### ISSUE TITLE
Where to hook events for gaining and losing input from server?

### ISSUE THREAD

**Issue by sh1boot** [r-c-f/waynergy#89]
I see a 'resume' event, but it doesn't always trigger when flipping back and forth quickly.

In any case, I need to run `ddcutil setvcp 0x60 0x12` when I gain focus, and `ddcutil setvcp 0x60 0x11` when I lose it.  This way the active input on my monitor follows keyboard and mouse focus.

**Comment by r-c-f** [comment]
Does #90 suffice, or does it need to be more sophisticated?

**Comment by sh1boot** [comment]
Works exactly as expected, thanks!  Example fragment from config.ini:
```ini
[screen]
enter = ddcutil setvcp 0x60 0x11
exit = ddcutil setvcp 0x60 0x12
```

Thanks!

`ddcutil` turns out to be really slow to get my monitor to do anything, but maybe I can get to the bottom of that eventually.

**Comment by sh1boot** [comment]
(for the benefit of random google searchers)

`ddcutil` can be sped up by adding an argument like `-b 3`, which stops it having to auto-probe all the i2c buses to figure out where the the display is.

My value `3` comes from the `/dev/i2c-3` line item shown against the relevant monitor in `ddcutil detect`.
