### ISSUE TITLE
QUESTION: How to get WWWBack and WWWForward to work

### ISSUE THREAD

**Issue by hahuang65** [r-c-f/waynergy#9]
I followed the instructions [here](https://mfcallahan.blog/2021/02/16/making-the-mouse-forward-and-back-buttons-work-when-using-synergy-finally/) on my host machine (macOS), and nothing happens on my client machine (Arch Linux).

Wondering if I can see sent/received keystrokes in the log? I tried loglevel 9 with no luck.

**Comment by r-c-f** [comment]
88775845a5f37f9f0e6f1f8c37c6b9c9c031f2cf adds this to the debug logging. You'd need to add the keycodes to the `mac` keycode section. The symbols section you're using has them as
```
    key <I166>   {      [ XF86Back              ]       };                      
    key <I167>   {      [ XF86Forward           ]       };
```
so `<I166>` and `<I167>` are the somewhat-unintuitive names to define there.

**Comment by hahuang65** [comment]
Got it, so I'll need to add

```
<I166> = <whatever shows up in debug log>
```

to my `~/.xkb/keycodes` file?

**Comment by hahuang65** [comment]
Is there any chance we can get a bump on the AUR package for this version?

**Comment by r-c-f** [comment]
That is what you'd do, yes. As for the AUR package, it is a VCS package, so rebuilding normally will always build the latest version regardless of how old the PKGBUILD itself happens to be.

**Comment by hahuang65** [comment]
Ah okay, so I've just been using `wev`. In any case, it doesn't look like the Synergy server is sending over the keycodes. I can see when I'm directly connected to the client, it's keycode 275 and 276... but when it's with Synergy, I just don't get the clicks.

**Comment by r-c-f** [comment]
They won't register with wev unless there is a corresponding keycode in the layout, unfortunately.

**Comment by hahuang65** [comment]
Oh, okay, so I'm not super sure how to move forward on this. With `--log-level 9` I don't see what the keycodes are for my mouse 5 and mouse 6 buttons that I'm supposed to assign to `I166` and `I167`.

**Comment by r-c-f** [comment]
I've pushed a commit that will add mouse buttons to the debug log, in the hope that it's at least sending them that way.

**Comment by hahuang65** [comment]
I've edited my `xkb` keymap with these changes:

```
default xkb_keycodes "mac" {
	minimum = 8;
	maximum = 276;
  <I166>  = 275;
  <I167>  = 276;
};
```

But no dice.

I see your changes that log the mouse buttons. But the mouse5 and mouse6 buttons never show up. I only see mouse1,2,3.

**Comment by r-c-f** [comment]
If that's the case, the next question is whether or not you get any events with the official client on X. If so, they're using a weird message type I'd need to handle; if not, it becomes a synergy bug on the server side.

**Comment by donjan** [comment]
I'm also stuck with this.

Im using Ubuntu 20.04 with an input-leap server and a Ubuntu 22.04 with waynergy client.
Maybe relevant: waynergy reports `[WARN] uinput does not support xkb keymaps -- use raw-keymap instead` on launch. I'll provide detailed logs if useful.

My mouse side buttons work fine directly on the client, but not on the waynergy client via the protocol.
They also work fine between an input-leap server and an input-leap client via the protocol.

When pressing a side button (e.g. forward), input-leap with `Debug1` logs:
```
[2022-08-24T16:47:53] DEBUG1: event: ButtonPress button=9
	../src/lib/platform/XWindowsScreen.cpp,1495
[2022-08-24T16:47:53] DEBUG1: onMouseDown id=5
	../src/lib/server/Server.cpp,1697
[2022-08-24T16:47:53] DEBUG1: send mouse down to "artox" id=5
	../src/lib/server/ClientProxy1_0.cpp,337
[2022-08-24T16:47:53] DEBUG1: event: ButtonRelease button=9
	../src/lib/platform/XWindowsScreen.cpp,1506
[2022-08-24T16:47:53] DEBUG1: onMouseUp id=5
	../src/lib/server/Server.cpp,1710
[2022-08-24T16:47:53] DEBUG1: send mouse up to "artox" id=5
	../src/lib/server/ClientProxy1_0.cpp,344
```
waynergy with `-L debug` receives nothing.
I've compiled the latest master as of today, but it doesn't print anything on mouse button presses. It does log `keycode: XX, state Y` on keyboard presses.

Issue https://github.com/r-c-f/waynergy/issues/27 doesn't provide know-how on mouse button debugging.

Adding `mousebutton(X)` entries in the serverside configuration, as detailed by the blog post in the OP, has no effect.

I'm not sure I understand https://github.com/r-c-f/waynergy/issues/9#issuecomment-853436413 properly: since I'm on Linux on both server and client, where would my keymap config file go exactly (`~/.config/waynergy` or the common `~/.xkb`)? (I don't want to change anything for any other programs)
What should the filename be (`~/.xkb/keymap/custom` or is it freeform)?
Also, I assume all this is on the client?
Should I change the string portion from the [examples](https://github.com/r-c-f/waynergy/blob/master/doc/xkb/keycodes/win)
```
default xkb_keycodes "win" {
```
to something like `"linux"` or is it not relevant?
Do I also need to add a https://github.com/r-c-f/waynergy/blob/master/doc/config-example/xkb_keymap somewhere?
I'm not too experienced with xkb and the local README.md is a bit scarce on these details ;)
Thanks for considering my questions.

Side note: created a ticket over at input-leap: https://github.com/input-leap/input-leap/issues/1492, but here seems to be the more appropriate place.

**Comment by r-c-f** [comment]
@donjan If it's working in the official client, here is definitely the appropriate place. From your log it looks like they're sending buttons beyond the map I use. Latest master should log buttons received; seeing that, and what `xev` reports for the working client, would allow for further progress (likely in the form of a way to map buttons to keys if this works as I expect).

**Comment by MYanello** [comment]
Wanted to pop in and help since I'm stuck here as well. My xev output when my mouse is connected directly to the client is here. Button 8 is back and 9 is forward.
```
ButtonPress event, serial 34, synthetic NO, window 0x800001,
    root 0x4a1, subw 0x0, time 18842006, (135,91), root:(235,260),
    state 0x0, button 8, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x800001,
    root 0x4a1, subw 0x0, time 18842095, (135,91), root:(235,260),
    state 0x0, button 8, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x800001,
    root 0x4a1, subw 0x0, time 18842111, (135,91), root:(235,260),
    state 0x0, button 9, same_screen YES

ButtonPress event, serial 34, synthetic NO, window 0x800001,
    root 0x4a1, subw 0x0, time 18842577, (135,91), root:(235,260),
    state 0x0, button 9, same_screen YES
```

My input-leap logs look the same as donjan's as well. Xev logs on client when connected through waynergy are empty.

**Comment by r-c-f** [comment]
With a direct connection, what does `wev` show?

**Comment by MYanello** [comment]
For wev forward: 
```
[13:      wl_pointer] button: serial: 24901; time: 19735451; button: 276 (extra), state: 1 (pressed)
[13:      wl_pointer] frame
[13:      wl_pointer] button: serial: 24902; time: 19735584; button: 276 (extra), state: 0 (released)
```
for wev back:
```
[13:      wl_pointer] button: serial: 24887; time: 19732693; button: 275 (side), state: 1 (pressed)
[13:      wl_pointer] frame
[13:      wl_pointer] button: serial: 24888; time: 19732792; button: 275 (side), state: 0 (released)
```

**Comment by r-c-f** [comment]
Does #46 yield the correct behavior?

**Comment by MYanello** [comment]
That seems to have broken left and right clicking; while not adding forward and back functionality. 
Any further logs I can provide here? I can't think of anything that would have changed in my logs

**Comment by MYanello** [comment]
Edited my config.ini to match the defaults, which matches my setup. Still no left, mid, right, or side buttons on my mouse. Scrolling and movement works. config.ini below:

```host = marcus-desktop
#port = 28400
#name = localhost
#width = 1024
#height = 768

[screensaver]
start = pkill -SIGUSR1 swayidle
#stop = pkill swaylock

[idle-inhibit]
method = key
keyname = HYPR

[tls]
enable = false
tofu = false

[log]
level = 3
mode = a
path = /tmp/waynergy.log

[raw-keymap]
offset=8
offset_on_explicit=false
# remote = local
347=133 #Lmeta
348=133 #Rmeta
331=113 #left
328=111 #up
333=114 #right
336=116 #down
339=119 #del
329=112 #pgup
337=117 #pgdn
285=105 #rctrl
312=108 #ralt
[id-keymap]
#media
57517=121 #mute
57518=122 #voldn
57519=123 #volup
57522=174 #stop
57521=173 #back
57523=172 #play
57520=171 #next

[button-map]
0=0 #no button
1=0x110 #btnleft
2=0x112 #btnmid
3=0x111 #btnright
276=0x114 #btn extra
275=0x113 #btnside
```

**Comment by r-c-f** [comment]
You should be able to remove the config section now; the issue was in the input backend initialization (uinput needs the map to set up the virtual mouse ahead of time).

**Comment by MYanello** [comment]
It's working now, except the forward and back are flipped. Also, it doesn't seem that my config.ini for the button map are being respected to flip them back (not sure if that's even still implemented).

**Comment by r-c-f** [comment]
It is, but the 276 and 275 would disrupt things. But I'll reverse them in the default, and merge after verifying the KDE protocol still works.

**Comment by r-c-f** [comment]
Thank you immensely for your help, by the way; I don't own one of these and would otherwise be entirely in the dark.

**Comment by MYanello** [comment]
I am the one who owes thanks. Wayland input-leap support is the last thing keeping me from using Wayland/Linux as my daily driver. I think with this bug squashed you are at parity in terms of wayland vs x11 as a client.

**Comment by donjan** [comment]
How awesome is that: looking at the issue a day later and everything is resolved.
Commenting primarily to confirm that the mouse side buttons work for me as well with the current master ([3ef8bc8](https://github.com/r-c-f/waynergy/commit/3ef8bc87a82f30246d47a4df07507a3047f9cda6)).

Thank you @r-c-f for putting in the effort, and thanks @MYanello for helping here and over at input-leap.
